name: Angular Build and Deploy

on:
  push:
    branches: 
    - main


jobs:
  build:
    runs-on: ubuntu-lates

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Build Angular app to prod
      run: pnpm install && pnpm run build:prod
        
    - name: Deploy to GitHub pages
      uses: JamesIves/
      github-pages-deploy-action@release/v2
      with:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      BASE_BRANCH: main
      BRANCH: prod
      FOLDER: Monster_Slayer/dist/browser